### PR TITLE
create GETTING_STARTED

### LINKED ISSUE #8: Update README
Overview, descriptions, and instructions need to be updated.

- [x] The [README.md](https://github.com/vabarbosa/Fun-with-Quantum/blob/main/README.md) notebook needs to be reviewed and updated accordingly to fix broken links, typos, etc.

Instructions on how users can run the various notebooks should be separated from the README and documented in a separate GETTING_STARTED document (see #9)

### LINKED ISSUE #9: Create GETTING_STARTED document
Instructions on how users can run the various notebooks should be separated from the README (see #8) and documented in a separate GETTING_STARTED document

- [x] A `GETTING_STARTED.md` document outlining instructions for running the notebooks
   - in a local environment
   - using the [Binder service](https://mybinder.org/)

### PR DESCRIPTION
**Pull request by vabarbosa**
this PR  

- Fixes #8  by removing the set up instructions which would be included in the getting started doc and updating some outdated links  
- Fixes #9  by creating a getting started doc and adding instructions for setting up your environment to run the notebooks

### CODE REVIEW

**Review by oyin-bee — CHANGES_REQUESTED** [review]
Links ok
Getting started, suggested amendments:
Gettting = Getting

**Review by oyin-bee — COMMENTED** [review]
requirements.txt looks ok to me

**Review by oyin-bee — CHANGES_REQUESTED** [review]
READ ME. 
Most links are ok
Suggested amendments:
Introductions = Introduction
A spectrum of Quantum Computing demos and Serious Games for Quantum Computing (that illustrate superposition, interference and entanglement) will **being** made available on this device for an engaging introduction to Quantum Computing. = be

oberservables = observables

https://mybinder.org/v2/gh/JanLahmann/Fun-with-Quantum/master?filepath=Merminâ€“Peres-Game.ipynb = does not load

**Comment by vabarbosa** [comment]
@oyin-bee  i have made the suggested updates in the README.md. thanks!

**Review by oyin-bee — APPROVED** [review]
Hi Va, everything seems ok💯 Thank you

**Pull request merged**
