### PR TITLE
Update GHZ game

### LINKED ISSUE #2: Update Simple Quantum Implementation for Boolean satisfiability problems
The [Simple Quantum Implementation for Boolean satisfiability problems](https://github.com/vabarbosa/Fun-with-Quantum/blob/main/3sat.ipynb) notebook needs to be updated for Qiskit 1.2 and fix any broken links, typo, etc.

- [ ] Run through and update `3sat.ipynb` code cells
- [ ] Review and update `3sat.ipynb` content

Links
- [Qiskit 1.0 Migration Guide](https://docs.quantum.ibm.com/migration-guides)
- [Qiskit SDK release notes](https://docs.quantum.ibm.com/api/qiskit/release-notes)

### LINKED ISSUE #4: Update GHZ Game
The [GHZ Game](https://github.com/vabarbosa/Fun-with-Quantum/blob/main/GHZ-Game.ipynb) notebook needs to be updated for Qiskit 1.2 and fix any broken links, typo, etc.

- [x] Run through and update `GHZ-Game.ipynb` code cells
    - will require also updating the [`GHZGame/ghzGame.py`](https://github.com/vabarbosa/Fun-with-Quantum/blob/main/GHZGame/ghzGame.py) script
- [x] Review and update `GHZ-Game.ipynb` content

Links
- [Qiskit 1.0 Migration Guide](https://docs.quantum.ibm.com/migration-guides)
- [Qiskit SDK release notes](https://docs.quantum.ibm.com/api/qiskit/release-notes)

### PR DESCRIPTION
**Pull request by vabarbosa**
Fixes #4 

this PR updates 
- the GHZ Game notebook so it can be run with Qiskit 1.2 and also updates an outdated link
- the GHZ Game python file so it can run with Qiskit 1.2

### CODE REVIEW

**Review by oyin-bee — COMMENTED** [review]
GHZ-Game JupyterLab file
Suggested amendments: Errors on Cell 4, 16, 17, 18, 22, 26, 31, 32, 35, 37, 39, 41, 43, 46, 48, 50, 56, 58, 60

ghzGame.py
Unable to view python file on laptop.

**Comment by vabarbosa** [comment]
> GHZ-Game JupyterLab file Suggested amendments: Errors on Cell 4, 16, 17, 18, 22, 26, 31, 32, 35, 37, 39, 41, 43, 46, 48, 50, 56, 58, 60

@oyin-bee what are some of these errors you are seeing? did you also have the `GHZGame/ghzGame.py` downloaded before running through this notebook?


> ghzGame.py Unable to view python file on laptop.

this file is used by the notebook so if you are able to run the notebooks successfully then it means this should be OK too.

**Review by oyin-bee — CHANGES_REQUESTED** [review]
All good, please see error generated in Jupyter

Screenshot 2024-09-20 153806

**Review by oyin-bee — CHANGES_REQUESTED** [review]
Hi Va, A couple of errors were generated, please see screenshots

Screenshot 2024-09-25 165649
Screenshot 2024-09-25 165704
Screenshot 2024-09-25 165720

**Review by oyin-bee — CHANGES_REQUESTED** [review]
Hi Va, re GHZ-Game.ipynb

The code is ok

Please see suggested grammar and spelling changes below: (Line numbering is derived from updated version in split view)

Line 49 Prerequisites = Prerequisites
Line 226 Not rendering text
Line 283 If you are confident with your choices try it out here = If you are confident with your choices, try them out here. (add comma)
Line 283 strategie = strategy
Line 314  Why has the other team a 100% winning strategie while your team does not? =  Why does the other team have a 100% winning strategy while your team does not? (add ‘have’; strategy spelling)
Line 316 To find out what they do differently you talk = to find out what they do differently, you talk (add comma)
Line 390 is, but = is(remove comma) but
Line 435 Before we start we need = Before we start, we need
Line 476 Being = being 
Line 539 However, (add comma)
Line 730 if you need help, (add comma)
Line 963 state.The (add space)
Line 1235 Entaglement = Entanglement
Line 1239 Pragraphs = Paragraphs

Thank you
I could not add comments - see screenshot below
Screenshot 2024-10-01 124718

**Pull request merged**
